version: "3.9"
services:
  app:
    image: lemariva/homeassistant-bluetooth-mesh-app
    volumes:
      - ./docker/config:/var/lib/bluetooth/mesh
    restart: "always"
    network_mode: "host"
    privileged: true
    tty: true

